version: "3"
volumes:
  db_data:
    driver: local
services:
  db:
    image: postgres:15.3
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "strapi"
      POSTGRES_DB: "strapi"
      POSTGRES_PASSWORD: "strapi"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  strapi:
    build: .
    image: ghcr.io/valuable-promo/headless:dev
    command: npm run develop
    env_file:
      - .env
    ports:
      - "1337:1337"
    depends_on:
      - db
    volumes:
      - ./:/app
