name: Production

on:
  push:
    tags: [v*]

jobs:
  build:
    uses: valuable-promo/infra/.github/workflows/build-production.yaml@main
    with:
      username: ${{ github.actor }}
    secrets:
      PASSWORD: ${{ secrets.GITHUB_TOKEN }}
